package org.goodday.mybatis.mapper;

import java.util.List;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Param;
import org.goodday.mybatis.entity.User;
import org.goodday.mybatis.entity.UserExample;
import org.goodday.mybatis.entity.Target;
import org.goodday.mybatis.entity.TargetExample;

public interface UserMapper extends BaseMapper<User> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu May 08 12:17:56 CST 2025
     */
    long countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu May 08 12:17:56 CST 2025
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu May 08 12:17:56 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu May 08 12:17:56 CST 2025
     */
    int insert(User row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu May 08 12:17:56 CST 2025
     */
    int insertSelective(User row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu May 08 12:17:56 CST 2025
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu May 08 12:17:56 CST 2025
     */
    User selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu May 08 12:17:56 CST 2025
     */
    int updateByExampleSelective(@Param("row") User row, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu May 08 12:17:56 CST 2025
     */
    int updateByExample(@Param("row") User row, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu May 08 12:17:56 CST 2025
     */
    int updateByPrimaryKeySelective(User row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu May 08 12:17:56 CST 2025
     */
    int updateByPrimaryKey(User row);

    interface TargetMapper {
        long countByExample(TargetExample example);

        int deleteByExample(TargetExample example);

        int deleteByPrimaryKey(String id);

        int insert(Target row);

        int insertSelective(Target row);

        List<Target> selectByExample(TargetExample example);

        Target selectByPrimaryKey(String id);

        int updateByExampleSelective(@Param("row") Target row, @Param("example") TargetExample example);

        int updateByExample(@Param("row") Target row, @Param("example") TargetExample example);

        int updateByPrimaryKeySelective(Target row);

        int updateByPrimaryKey(Target row);
    }
}