package org.goodday.mybatis.entity;

import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;

import java.math.BigDecimal;
import java.util.Date;

@Data
@TableName("t_target")
public class Target {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_target.id
     *
     * @mbg.generated Wed May 07 21:54:58 CST 2025
     */
    @TableId
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_target.index_name
     *
     * @mbg.generated Wed May 07 21:54:58 CST 2025
     */
    private String indexName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_target.value
     *
     * @mbg.generated Wed May 07 21:54:58 CST 2025
     */
    private BigDecimal value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_target.data_time
     *
     * @mbg.generated Wed May 07 21:54:58 CST 2025
     */
    private Date dataTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_target.id
     *
     * @return the value of t_target.id
     *
     * @mbg.generated Wed May 07 21:54:58 CST 2025
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_target.id
     *
     * @param id the value for t_target.id
     *
     * @mbg.generated Wed May 07 21:54:58 CST 2025
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_target.index_name
     *
     * @return the value of t_target.index_name
     *
     * @mbg.generated Wed May 07 21:54:58 CST 2025
     */
    public String getIndexName() {
        return indexName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_target.index_name
     *
     * @param indexName the value for t_target.index_name
     *
     * @mbg.generated Wed May 07 21:54:58 CST 2025
     */
    public void setIndexName(String indexName) {
        this.indexName = indexName == null ? null : indexName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_target.value
     *
     * @return the value of t_target.value
     *
     * @mbg.generated Wed May 07 21:54:58 CST 2025
     */
    public BigDecimal getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_target.value
     *
     * @param value the value for t_target.value
     *
     * @mbg.generated Wed May 07 21:54:58 CST 2025
     */
    public void setValue(BigDecimal value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_target.data_time
     *
     * @return the value of t_target.data_time
     *
     * @mbg.generated Wed May 07 21:54:58 CST 2025
     */
    public Date getDataTime() {
        return dataTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_target.data_time
     *
     * @param dataTime the value for t_target.data_time
     *
     * @mbg.generated Wed May 07 21:54:58 CST 2025
     */
    public void setDataTime(Date dataTime) {
        this.dataTime = dataTime;
    }

    @Override
    public String toString() {
        // 打印所有内容
        return "Target{" +
                "id='" + id + '\'' +
                ", indexName='" + indexName + '\'' +
                ", value=" + value +
                ", dataTime=" + dataTime +
                '}';
    }
}